name: Deploy to Production

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/main' || github.event.inputs.environment == 'staging'
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.anygle.app
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to Staging Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USER }}
        key: ${{ secrets.STAGING_SSH_KEY }}
        port: ${{ secrets.STAGING_PORT }}
        script: |
          cd /opt/anygle
          docker-compose -f docker-compose.yml pull
          docker-compose -f docker-compose.yml up -d --remove-orphans
          docker-compose exec -T backend php artisan migrate --force
          docker-compose exec -T backend php artisan optimize
          docker-compose exec -T backend php artisan queue:restart
          docker system prune -f

    - name: Health Check
      run: |
        sleep 30
        curl -f https://staging.anygle.app/api/health || exit 1

  deploy-production:
    if: startsWith(github.ref, 'refs/tags/v') || github.event.inputs.environment == 'production'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://anygle.app
    needs: [deploy-staging]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to Production Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USER }}
        key: ${{ secrets.PRODUCTION_SSH_KEY }}
        port: ${{ secrets.PRODUCTION_PORT }}
        script: |
          cd /opt/anygle
          
          # Backup database before deploy
          docker-compose exec -T mysql mysqldump -u root -p${{ secrets.DB_PASSWORD }} anygle > backup-$(date +%Y%m%d-%H%M%S).sql
          
          # Pull new images
          docker-compose -f docker-compose.prod.yml pull
          
          # Rolling update
          docker-compose -f docker-compose.prod.yml up -d --no-deps --scale backend=2 backend
          sleep 10
          docker-compose -f docker-compose.prod.yml up -d --no-deps --scale backend=1 backend
          
          # Run migrations
          docker-compose exec -T backend php artisan migrate --force
          docker-compose exec -T backend php artisan optimize
          docker-compose exec -T backend php artisan queue:restart
          docker-compose exec -T backend php artisan event:cache
          docker-compose exec -T backend php artisan view:cache
          
          # Cleanup
          docker system prune -f

    - name: Health Check
      run: |
        sleep 30
        curl -f https://anygle.app/api/health || exit 1

    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#deployments'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        fields: repo,message,commit,author,action,eventName,ref,workflow
      if: always()

  rollback:
    if: failure()
    runs-on: ubuntu-latest
    needs: [deploy-production]
    
    steps:
    - name: Rollback to Previous Version
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USER }}
        key: ${{ secrets.PRODUCTION_SSH_KEY }}
        port: ${{ secrets.PRODUCTION_PORT }}
        script: |
          cd /opt/anygle
          docker-compose -f docker-compose.prod.yml down
          docker-compose -f docker-compose.prod.yml up -d
          
          # Restore from backup if needed
          # mysql -u root -p${{ secrets.DB_PASSWORD }} anygle < latest-backup.sql