name: Database Migration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      migration_type:
        description: 'Migration type'
        required: true
        default: 'migrate'
        type: choice
        options:
          - migrate
          - rollback
          - fresh
          - seed

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Migration
      uses: appleboy/ssh-action@master
      with:
        host: ${{ github.event.inputs.environment == 'production' && secrets.PRODUCTION_HOST || secrets.STAGING_HOST }}
        username: ${{ github.event.inputs.environment == 'production' && secrets.PRODUCTION_USER || secrets.STAGING_USER }}
        key: ${{ github.event.inputs.environment == 'production' && secrets.PRODUCTION_SSH_KEY || secrets.STAGING_SSH_KEY }}
        port: ${{ github.event.inputs.environment == 'production' && secrets.PRODUCTION_PORT || secrets.STAGING_PORT }}
        script: |
          cd /opt/anygle
          
          # Create backup before migration
          if [ "${{ github.event.inputs.migration_type }}" != "seed" ]; then
            docker-compose exec -T mysql mysqldump -u root -p${{ secrets.DB_PASSWORD }} anygle > backup-pre-migration-$(date +%Y%m%d-%H%M%S).sql
          fi
          
          case "${{ github.event.inputs.migration_type }}" in
            migrate)
              docker-compose exec -T backend php artisan migrate --force
              ;;
            rollback)
              docker-compose exec -T backend php artisan migrate:rollback --force
              ;;
            fresh)
              docker-compose exec -T backend php artisan migrate:fresh --force
              ;;
            seed)
              docker-compose exec -T backend php artisan db:seed --force
              ;;
          esac
          
          # Clear caches
          docker-compose exec -T backend php artisan cache:clear
          docker-compose exec -T backend php artisan config:clear