name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate Changelog
      id: changelog
      run: |
        echo "CHANGELOG<<EOF" >> $GITHUB_ENV
        git log --pretty=format:"- %s (%h)" $(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo HEAD~10)..HEAD >> $GITHUB_ENV
        echo "" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes in this Release
          ${{ env.CHANGELOG }}
          
          ## Docker Images
          - Frontend: `ghcr.io/${{ github.repository }}/frontend:${{ github.ref_name }}`
          - Backend: `ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }}`
          - WebSocket: `ghcr.io/${{ github.repository }}/websocket:${{ github.ref_name }}`
          - Nginx: `ghcr.io/${{ github.repository }}/nginx:${{ github.ref_name }}`
          
          ## Deployment
          ```bash
          docker-compose -f docker-compose.prod.yml pull
          docker-compose -f docker-compose.prod.yml up -d
          ```
        draft: false
        prerelease: false

  notify:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
    - name: Notify Discord
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: '🚀 New release ${{ github.ref_name }} is live! https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}'

    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: success
        channel: '#releases'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        fields: repo,message,commit,author,action,eventName,ref,workflow
        text: '🚀 New release ${{ github.ref_name }} is live!'